name: Verify compile

on: [push, pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
      - name: Publish PDF as actions assets
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: thuthesis-example.pdf

      - name: cp artifact
        run: |
          mkdir ./public
          cp thuthesis-example.pdf ./public

      - name: Deploy PDF
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: latest
          force_orphan: true