name: Verify and sync

on: [push, pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make test

      - name: Publish PDF as actions assets
        uses: actions/upload-artifact@v2
        with:
          name: Example-PDFs
          path: public-test/*.pdf

      # - name: Deploy PDF to latest branch
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: github.ref == 'refs/heads/master'
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public-test
      #     publish_branch: latest
      #     force_orphan: true

  sync:
    runs-on: ubuntu-latest
    name: Sync to other git service
    if: always() && github.repository_owner == 'SUSTech-CRA'
    needs: build_latex
    steps:

    # - name: Push to gitee
    #   run: |
    #     mkdir -p /tmp/tmp_push
    #     cd /tmp/tmp_push
    #     git clone --bare https://github.com/liziwl/sustech-master-thesis.git this_repo
    #     cd this_repo
    #     git push --force --mirror "https://${USER}:${PERSONAL_TOKEN}@${REPO_URL}"
    #   env:
    #     USER: ${{ secrets.GITEE_USER }}
    #     PERSONAL_TOKEN: ${{ secrets.GITEE_PERSONAL_TOKEN }}
    #     REPO_URL: "gitee.com/liziwl/sustech-master-thesis.git"

    - name: Push to sustech-git
      run: |
        mkdir -p /tmp/tmp_push2
        cd /tmp/tmp_push2
        git clone --bare https://github.com/SUSTech-CRA/sustech-master-thesis.git this_repo
        cd this_repo
        git push --force --mirror "https://${USER}:${PERSONAL_TOKEN}@${REPO_URL}"
      env:
        USER: project_160_bot
        PERSONAL_TOKEN: ${{ secrets.GITLAB_PERSONAL_TOKEN }}
        REPO_URL: "mirrors.sustech.edu.cn/git/liziwl/sustech-master-thesis.git"
