name: Verify and sync

on: [push, pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        texlive: [TL2020-historic, latest]
        # 多版本 TexLive 兼容性测试
    container: texlive/texlive:${{ matrix.texlive }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Meta-data normalization
        run: python test/update-dist.py --dev

      - name: run texlive docker container
        run: make doc test

      - name: Publish PDF as actions assets
        uses: actions/upload-artifact@v2
        with:
          name: Example-PDFs-texlive-${{ matrix.texlive }}
          path: |
            sustechthesis.pdf
            public-test/*.pdf

      # - name: Deploy PDF to latest branch
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: github.ref == 'refs/heads/master'
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public-test
      #     publish_branch: latest
      #     force_orphan: true

  sync:
    runs-on: ubuntu-latest
    name: Sync to other git service
    if: github.repository_owner == 'SUSTech-CRA'
    timeout-minutes: 10
    concurrency: 
      group: sync-job
      cancel-in-progress: true
    # needs: build_latex
    steps:

    # - name: Push to gitee
    #   run: |
    #     mkdir -p /tmp/tmp_push
    #     cd /tmp/tmp_push
    #     git clone --bare https://github.com/liziwl/sustech-master-thesis.git this_repo
    #     cd this_repo
    #     git push --force --mirror "https://${USER}:${PERSONAL_TOKEN}@${REPO_URL}"
    #   env:
    #     USER: ${{ secrets.GITEE_USER }}
    #     PERSONAL_TOKEN: ${{ secrets.GITEE_PERSONAL_TOKEN }}
    #     REPO_URL: "gitee.com/liziwl/sustech-master-thesis.git"

    - name: Push to sustech-git
      run: |
        tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
        echo $tmp_dir
        cd $tmp_dir
        git clone --bare "${GITHUB_REPO_URL}" this_repo
        cd this_repo
        git push --force --mirror "https://${USER}:${PERSONAL_TOKEN}@${REMOTE_REPO_URL}"
      env:
        USER: project_160_bot
        PERSONAL_TOKEN: ${{ secrets.GITLAB_PERSONAL_TOKEN }}
        GITHUB_REPO_URL: https://github.com/SUSTech-CRA/sustech-master-thesis.git
        REMOTE_REPO_URL: "mirrors.sustech.edu.cn/git/liziwl/sustech-master-thesis.git"
